server:
  servlet:
    session:
      tracking-modes: cookie

fit:
  #file-upload-path: d:/tmp  #文件上传目录(不配置的话为java.io.tmpdir目录)
  muti-datasource-open: false #是否开启多数据源(true/false)
  spring-session-open: false #是否开启spring session,如果是多机环境需要开启(true/false)
  session-invalidate-time: 1800 #session失效时间(只在单机环境下生效，多机环境在SpringSessionConfig类中配置) 单位：秒
  session-validation-interval: 900 #多久检测一次失效的session(只在单机环境下生效) 单位：秒

###################  beetl配置  ###################
beetl:
  delimiter-statement-start: \@   #开始结束标签(yaml不允许@开头)
  delimiter-statement-end: null
  resource-tagroot: common/tags   #自定义标签文件Root目录和后缀
  resource-tagsuffix: tag
  resource-auto-check: true #是否检测文件变化,开发用true合适，但线上要改为false

###################  spring配置  ###################
spring:
  profiles:
    active: '@profiles.active@'
  aop:
    proxy-target-class: true #false为启用jdk默认动态代理,true为cglib动态代理
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    format:
      date: yyyy-MM-dd
      time: HH:mm:ss
      date-time: yyyy-MM-dd HH:mm:ss
    http:
      converters:
        preferred-json-mapper: fastjson
    multipart:
      max-file-size: 100MB #最大文件大小
      max-request-size: 100MB #最大请求大小
  # 模板引擎
  thymeleaf:
    prefix: classpath:/templates/
    encoding: utf-8
    suffix: .html
    cache: false  # 禁用缓存
    mode: HTML
    servlet:
      content-type: text/html
  # 静态资源
  resource:
    static-locations: classpath:/static/,classpath:/html/

###################  mybatis-plus配置  ###################
mybatis-plus:
  mapper-locations: classpath*:com/fit/**/mapping/*.xml
  typeAliasesPackage: com.fit.modular.system.model
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    logic-not-delete-value: 1
    logic-delete-value: 0
    refresh-mapper: true
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用